### ISSUE TITLE
Add new VTuber theme Airani Iofifteen

### ISSUE THREAD

**Issue by Jersk41** [13atm01/GRUB-Theme#17]
Can we add more VTuber GRUB theme? i was searching Airani Iofifteen theme but not find any, so i currently making one and thinking to add that theme in this repository. 
Preview :
![preview](https://github.com/13atm01/GRUB-Theme/assets/63460438/9628223a-3113-43a3-b04a-adb6882ab0df)

**Comment by 13atm01** [comment]
Sure, you can add your own version to this repository, I'll check it first

For copyright, you can tell me links social media those VTuber like YouTube and Twitter. and you can tell me your real name to add in the installation description.

**Comment by 13atm01** [comment]
- Looks like you forgot to remove a bit white background on the character render :sweat_smile: 

![background](https://github.com/13atm01/GRUB-Theme/assets/75361601/cab89ad7-b65b-41d5-8d72-db03916eb429)

- I think the character image is a little blurry :thinking: 

![background2](https://github.com/13atm01/GRUB-Theme/assets/75361601/d5c9979a-25f9-4f14-ab2b-06c2e858fce3)

**Comment by Jersk41** [comment]
Ouh sorry, i didint realize that until now, i will try fix that white background and blurry image. 

For attribution
-  Airani Iofifteen image get from [pixiv](https://www.pixiv.net/en/artworks/91147966)
- YT Link = https://www.youtube.com/channel/UCfrWoRGlawPQDQxxeIDRP0Q
- Twitter = https://twitter.com/airaniiofifteen
- My Full name is also available on my github profile

**Comment by 13atm01** [comment]
great, I'll check again

**Comment by 13atm01** [comment]
I've included your name in the installation description, now just upload it.

![240120_18h21m02s_screenshot](https://github.com/13atm01/GRUB-Theme/assets/75361601/24e8fdf8-b3db-4d17-94ed-bd24465d4087)

**Comment by Jersk41** [comment]
Oke Thank you 👍🏻  We close the issue after that then?

**Comment by 13atm01** [comment]
All is done, you can see here [README.md](https://github.com/13atm01/GRUB-Theme/blob/master/README.md) for copyright and preview, I have also uploaded it on the [pling/gnome-look](https://www.gnome-look.org/p/1760905/) website, and also added it to the tag [Releases](https://github.com/13atm01/GRUB-Theme/releases). You can promote it to your friends now

Yes I will close this issue, you can open a discussion in the tab [Discussions](https://github.com/13atm01/GRUB-Theme/discussions) if you want to share your ideas with other people who visit this repository
