### ISSUE TITLE
[Functionality request] Images gets streched on other than 16:9 proportions

### ISSUE THREAD

**Issue by kwakczuszka** [13atm01/GRUB-Theme#21]
Is there a workaround for example for 3:2?

**Comment by 13atm01** [comment]
Sorry I don't know how to change the scale to 3:2

But you can try changing the resolution according to your PC

You can change the contents of the file in the directory /etc/default/grub, change the "GRUB_GFXMODE=", you can change it to auto or enter the desired resolution like 1920x1080
