### ISSUE TITLE
Add a new VTUBER Theme: Kobo Kanaeru

### ISSUE THREAD

**Issue by mushonnip** [13atm01/GRUB-Theme#7]
Can we have a new vtuber theme (Kobo Kanaeru)? I currently making this for personal use.

**Comment by 13atm01** [comment]
> Can we have a new vtuber theme (Kobo Kanaeru)? I currently making this for personal use.

Sure :+1: , you can make a pull request, but before I merge it, I need to see the result of your version

**Comment by 13atm01** [comment]
And may I give you a little advice and ask for your help? like help me in gathering resources

**Comment by 13atm01** [comment]
For example providing images of character without background, official links from VTuber such as Twitter and Youtube for copyright, and sorry I have to know your full name for copyright too

**Comment by mushonnip** [comment]
I just finished the design, here is the preview.
![kobo-grub2-theme](https://user-images.githubusercontent.com/15305192/194015528-7b8af410-adfd-4628-b841-d86f2a8e6e8e.png)

Art Source: https://www.pixiv.net/en/artworks/97224161 (I haven't ask for permission for this use)
I haven't test this in [grub2-theme-previewer](https://github.com/hartwork/grub2-theme-preview) or my real device. I will make a pull request if I have tested it.

Additional:
- I designed for 16:9 aspect ratio, my idea is to design for every common aspect ratio for the sake of proper look for everyone.  This can be achieved by modify the installer script.
- For my full name, you can look into my github profile
- Advice is welcome

**Comment by 13atm01** [comment]
You can do a pull request now, for testing, let me do it on my real device, and if there is an error I will immediately contact you back

You don't need to set the aspect ratio, because now almost everyone is using a monitor with a 16:9 aspect ratio, very rarely people use a ratio below or above that. Most importantly you set the background resolution at 1920x1080p.
